/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1 0x00u /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */

/*! @name PORTB0 (number 35), BACKLIGHT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BACKLIGHT_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_BACKLIGHT_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BACKLIGHT_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BACKLIGHT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BACKLIGHT_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BACKLIGHT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA12 (number 28), BUZZER
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BUZZER_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BUZZER_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BUZZER_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
